# Generated by Django 5.0.2 on 2024-03-12 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(choices=[(100, '100 seats'), (80, '80 seats'), (50, '50 seats')])),
                ('seats_per_row', models.IntegerField(default=10)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_rooms', to='cinemas.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_letter', models.CharField(max_length=1)),
                ('seat_number', models.IntegerField()),
                ('screening_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='screeningrooms.screeningroom')),
            ],
            options={
                'unique_together': {('screening_room', 'row_letter', 'seat_number')},
            },
        ),
    ]
