# Generated by Django 5.0.2 on 2024-03-12 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('screeningrooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showtime', models.DateTimeField(verbose_name='Showtime')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='Movie')),
                ('screening_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screeningrooms.screeningroom', verbose_name='Screening Room')),
            ],
        ),
    ]
