# Generated by Django 5.0.2 on 2024-03-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showtimes', '0002_showtime_ticket_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='ticket_price',
        ),
    ]
