# Generated by Django 5.0.2 on 2024-03-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimes', '0003_remove_showtime_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
