# Generated by Django 5.0.2 on 2024-03-29 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showtimes', '0004_showtime_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='price',
        ),
    ]
