# Generated by Django 5.0.2 on 2024-03-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimes', '0005_remove_showtime_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='seat_price',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6, verbose_name='Seat Price'),
        ),
    ]
