# Generated by Django 5.0.2 on 2024-03-30 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showtimes', '0006_showtime_seat_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='seat_price',
        ),
    ]
