# Generated by Django 5.0.2 on 2024-03-25 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment_comment_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_likes',
            new_name='likes',
        ),
    ]
