# Generated by Django 5.0.2 on 2024-03-29 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_seatreservation_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatreservation',
            name='total_price',
        ),
    ]
