# Generated by Django 5.0.2 on 2024-03-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('tmdb_id', models.IntegerField(unique=True, verbose_name='TMDb ID')),
                ('director', models.CharField(max_length=255, verbose_name='Director')),
                ('cast', models.TextField(verbose_name='Cast')),
                ('user_rating', models.FloatField(verbose_name='User Rating')),
                ('trailer_link', models.URLField(verbose_name='Trailer Link')),
                ('overview', models.TextField(verbose_name='Overview')),
                ('release_date', models.DateField(verbose_name='Release Date')),
                ('poster_path', models.URLField(verbose_name='Poster URL')),
                ('original_language', models.CharField(max_length=10, verbose_name='Original Language')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
