# Generated by Django 5.0.2 on 2024-03-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='age_rating',
            field=models.CharField(blank=True, max_length=10, verbose_name='Age Rating'),
        ),
    ]
