# Generated by Django 5.0.2 on 2024-03-23 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_age_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='age_rating',
        ),
    ]
